apiVersion: extensions/v1beta1
kind: Ingress
  name: ingress-service
  annotation:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  spec:
    rules:
      http:
        - path:
