apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress-deployment
spec:
  selector:
    matchLabels:
      app: postgress
  template:
    metadata:
      labels:
        app: postgress
    spec:
      containers:
      - name: myapp
        image: postgress
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: <Port>
