apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: stephengrider/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: 6379
            - name: PG_USER
              value: postgress
            - name: PG_HOST
              value: postgres-cluster-ip-service
            - name: PG_DATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                  secretKeyRef:
                    name: pgpassword
                    key: 